<a href="https://colab.research.google.com/github/Jyoti1706/tensorflow-certification/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow fundamentals

## Tensorflow intro

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
## Creating tensors with tf.contant()
scalar   = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
## Check number of dimensions of tensor (ndim stands for number of dimension)
scalar.ndim

0

In [8]:
## Create a vector and find dimension
vector = tf.constant([10,10])
print(vector, vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32) 1


In [10]:
## Create a matrix and find dimension
matrix = tf.constant([[10,10,32], [9,8,5]])
print(matrix, matrix.ndim)

tf.Tensor(
[[10 10 32]
 [ 9  8  5]], shape=(2, 3), dtype=int32) 2


In [11]:
## Create a another matrix and find dimension
another_matrix = tf.constant([[1.,2.,3.], [9.,8.,5.]], dtype=tf.float16)
print(another_matrix, another_matrix.ndim)

tf.Tensor(
[[1. 2. 3.]
 [9. 8. 5.]], shape=(2, 3), dtype=float16) 2


In [12]:
## Create a tensor and find dimension
tensor = tf.constant([[[1.,2.,3.], [9.,8.,5.]],
                      [[3.,2.2,3.2], [9.1,8.1,5.4]],
                      [[21.,42.,31.], [9.4,48.,56.]]], dtype=tf.float16)
print(tensor, tensor.ndim)

tf.Tensor(
[[[ 1.   2.   3. ]
  [ 9.   8.   5. ]]

 [[ 3.   2.2  3.2]
  [ 9.1  8.1  5.4]]

 [[21.  42.  31. ]
  [ 9.4 48.  56. ]]], shape=(3, 2, 3), dtype=float16) 3


### What we have created so far is

* Scalar: a single number (0 Dimension)
* Vector: a number with direction (1 Dimension) (e.g: speed)
* Matrix: a 2-D of array of number (2 Dimension)
* Tensor: a n-dimensional array of number (where n can be any number, 0-Dimensional tensor is a scalar, a 1-dimensional tensor is a vector

### Creating tensor with tf.variable

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
changeable = tf.Variable([10,2])
unchangeable = tf.constant([7,6])
changeable, unchangeable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>)

In [16]:
changeable[0] = 6

TypeError: ignored

In [17]:
changeable[0].assign(4)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 2], dtype=int32)>

In [18]:
unchangeable[0].assign(4)  ## as its constant the tensor values cannot be changed once assigned
unchangeable

AttributeError: ignored